mysite/blog/api/v1/urls.py
# from django.urls import path
from rest_framework.routers import DefaultRouter
from . import views

app_name = "api-v1"

router = DefaultRouter()
router.register("posts", views.PostViewSet, basename="post")
urlpatterns = router.urls

# urlpatterns = [
# path('', views.post_list, name='post-list'),
# path('create/', views.create_post, name='post-create'),
# path('', views.PostListApiView.as_view(), name='post-list'),
# path('post/<int:id>/', views.PostDetailApiView.as_view(), name='post-detail'),
#     path('', views.PostListApiView.as_view(), name='post-list'),
#     path('post/<int:pk>/', views.PostDetailApiView.as_view(), name='post-detail'),
# ]

mysite/blog/urls.py
from django.urls import path, include
from blog import views
from blog.feeds import LatestEntriesFeed

app_name = "blog"

urlpatterns = [
    path("", views.BlogView.as_view(), name="index"),
    path("<int:pid>/", views.BlogSingleView.as_view(), name="single"),
    path("comment/<int:pid>/", views.CommentView.as_view(), name="comment"),
    path("category/<str:cat_name>/", views.BlogView.as_view(), name="category"),
    path("tag/<str:tag_name>/", views.BlogView.as_view(), name="tag"),
    path("author/<int:author_profile_id>/", views.BlogView.as_view(), name="author"),
    # path('search/', views.blog_search, name='search'),
    path("api/v1/", include("blog.api.v1.urls")),
    path("rss/feed/", LatestEntriesFeed()),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth import views as auth_views
from rest_framework import permissions
from rest_framework.documentation import include_docs_urls
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {"static": StaticViewSitemap, "blog": BlogSitemap}

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls")),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("summernote/", include("django_summernote.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("captcha/", include("captcha.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-docs/", include_docs_urls(title="api sample")),
    # path('auth_login', accounts_views.LoginView.as_view(), name='auth_login'),
    path(
        "reset_password/", auth_views.PasswordResetView.as_view(), name="reset_password"
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # dev
    path(
        "swagger/api.json", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/website/urls.py
from django.urls import path
from website import views

app_name = "website"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("newsletter/", views.NewsletterView.as_view(), name="newsletter"),
]

mysite/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils.timezone import now
from taggit.managers import TaggableManager
from accounts.models import Profile


class Category(models.Model):
    name = models.CharField(max_length=255)

    class Meta:
        verbose_name_plural = "Categories"

    def __str__(self):
        return self.name


class Post(models.Model):
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    image = models.ImageField(upload_to="blog/", default="default.jpg")
    title = models.CharField(max_length=255)
    content = models.TextField()
    category = models.ManyToManyField(Category)
    tags = TaggableManager(blank=True)
    counted_view = models.PositiveIntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(default=now, null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]
        # verbose_name = 'پست'
        # verbose_name_plural = 'پست ها'

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("blog:single", kwargs={"pk": self.id})

    def get_absolute_api_url(self):
        return reverse("blog:api-v1:post-detail", kwargs={"pk": self.id})

    def get_snippet(self):
        return self.content[:40]


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    published_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-created_date"]

mysite/blog/forms.py
from django import forms
from blog.models import Comment

# from captcha.fields import CaptchaField


class CommentForm(forms.ModelForm):
    # captcha = CaptchaField()
    class Meta:
        model = Comment
        fields = ["post", "name", "email", "subject", "message"]

mysite/blog/api/v1/views.py
from django.utils import timezone
from rest_framework.viewsets import ModelViewSet
from rest_framework.permissions import IsAuthenticatedOrReadOnly
from rest_framework.filters import SearchFilter
from django_filters.rest_framework import DjangoFilterBackend
from ...models import Post
from .serializers import PostSerializer
from .permissions import IsOwnerOrReadOnly
from .filters import PostFilter, PostCustomOrderFilter
from .paginations import CustomPagination

# fbv
# @api_view()
# @permission_classes([IsAuthenticated])
# def post_list(request):
#     posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
#     if not request.user.is_authenticated:
#         posts = posts.filter(login_require=False)
#     serializer = PostSerializer(posts, many=True)
#     return Response(serializer.data)

# @api_view(['POST'])
# def create_post(request):
#     serializer = PostSerializer(data=request.data)
#     serializer.is_valid(raise_exception=True)
#     serializer.save()
#     return Response(serializer.data)

# ApiViews
# class PostListApiView(APIView):
#     permission_classes = [IsAuthenticatedOrReadOnly]

#     def get(self, request):
#         posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
#         if not request.user.is_authenticated:
#             posts = posts.filter(login_require=False)
#         serializer = PostSerializer(posts, many=True)
#         return Response(serializer.data)

#     def post(self, request):
#         serializer = PostSerializer(data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data)

# class PostDetailApiView(APIView):
#     permission_classes = [IsOwnerOrReadOnly]

#     def get(self, request, id):
#         posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
#         if not request.user.is_authenticated:
#             posts = posts.filter(login_require=False)
#         post = get_object_or_404(posts, pk=id)
#         serializer = PostSerializer(post)
#         return Response(serializer.data)

#     def put(self, request, id):
#         posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
#         if not request.user.is_authenticated:
#             posts = posts.filter(login_require=False)
#         post = get_object_or_404(posts, pk=id)
#         serializer = PostSerializer(post, data=request.data)
#         serializer.is_valid(raise_exception=True)
#         serializer.save()
#         return Response(serializer.data)

#     def delete(self, request, id):
#         posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
#         if not request.user.is_authenticated:
#             posts = posts.filter(login_require=False)
#         post = get_object_or_404(posts, pk=id)
#         post.delete()
#         return Response({'detail': 'item removed successfully'}, status=status.HTTP_204_NO_CONTENT)

# class PostListApiView(ListCreateAPIView):
#     serializer_class = PostSerializer
#     permission_classes = [IsAuthenticatedOrReadOnly]

#     def get_queryset(self):
#         posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
#         if not self.request.user.is_authenticated:
#             posts = posts.filter(login_require=False)
#         return posts

# class PostDetailApiView(RetrieveUpdateDestroyAPIView):
#     serializer_class = PostSerializer
#     permission_classes = [IsAuthenticatedOrReadOnly]

#     def get_queryset(self):
#         posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
#         if not self.request.user.is_authenticated:
#             posts = posts.filter(login_require=False)
#         return posts

# class PostViewSet(ViewSet):
#     permission_classes = [IsAuthenticatedOrReadOnly]
#     queryset = Post.objects.filter(status=True)
#     serializer_class = PostSerializer


class PostViewSet(ModelViewSet):
    permission_classes = [IsAuthenticatedOrReadOnly, IsOwnerOrReadOnly]
    serializer_class = PostSerializer
    pagination_class = CustomPagination
    filter_backends = [DjangoFilterBackend, SearchFilter, PostCustomOrderFilter]
    filterset_class = PostFilter
    search_fields = ["author__last_name", "title", "content"]
    ordering_fields = ["published_date", "counted_view"]
    # ordering = ['-published_date']

    def get_queryset(self):
        posts = Post.objects.filter(status=True, published_date__lte=timezone.now())
        if not self.request.user.is_authenticated:
            posts = posts.filter(login_require=False)
        return posts

mysite/templates/blog/blog-ads.html
{% load static %}
<div class="single-sidebar-widget ads-widget">
  <a href="#"><img class="img-fluid" src="{% static 'img/blog/ads-banner.jpg' %}" alt=""></a>
</div>

mysite/templates/blog/blog-newsletter.html
{% load static %}
<div class="single-sidebar-widget newsletter-widget">
  <h4 class="newsletter-title">Newsletter</h4>
  <p>
    Here, I focus on a range of items and features that we use in life
    without giving them a second thought.
  </p>
  <div class="form-group d-flex flex-row">
    <div class="col-autos">
      <div class="input-group">
        <div class="input-group-prepend">
          <div class="input-group-text">
            <i class="fa fa-envelope" aria-hidden="true"></i>
          </div>
        </div>
        <input
          type="text"
          class="form-control"
          id="inlineFormInputGroup"
          placeholder="Enter email"
          onfocus="this.placeholder = ''"
          onblur="this.placeholder = 'Enter email'"
        />
      </div>
    </div>
    <a href="#" class="bbtns">Subcribe</a>
  </div>
  <p class="text-bottom">You can unsubscribe at any time</p>
</div>

mysite/templates/blog/blog-popular-posts.html
{% load humanize %} 
{% load static %}
<div class="single-sidebar-widget popular-post-widget">
  <h4 class="popular-title">Popular Posts</h4>
  <div class="popular-post-list">
    {% for post in posts %}
    <div class="single-post-list d-flex flex-row align-items-center">
      <div class="thumb">
        <img class="img-fluid" src="{{post.image.url}}" alt="" />
      </div>
      <div class="details">
        <a href="{% url 'blog:single' pid=post.id %}"><h6>{{post.title}}</h6></a>
        <p>{{post.published_date|date:"d M Y"}}</p>
      </div>
    </div>
    {% endfor %}
  </div>
</div>

mysite/templates/blog/blog-post-categories.html
{% load static %}
<div class="single-sidebar-widget post-category-widget">
  <h4 class="category-title">Post Catgories</h4>
  <ul class="cat-list">
    {% for name,count in categories.items %}
    <li>
      <a href="{% url 'blog:category' cat_name=name %}" class="d-flex justify-content-between">
        <p>{{name}}</p>
        <p>{{count}}</p>
      </a>
    </li>
    {% endfor %}
  </ul>
</div>

mysite/templates/blog/blog-search.html
{% load static %}
<div class="single-sidebar-widget search-widget">
  <form class="search-form" action="{% url 'blog:index' %}" method="get">
    <input
      placeholder="Search Posts"
      name="s"
      type="text"
      onfocus="this.placeholder = ''"
      onblur="this.placeholder = 'Search Posts'"
    />
    <button type="submit"><i class="fa fa-search"></i></button>
  </form>
</div>

mysite/templates/blog/blog-single.html
{% extends 'base.html' %}
{% load static %}
{% load humanize %}
{% load blog_tags %}
{% block container %}
<!-- start banner Area -->
<section class="relative about-banner">
	<div class="overlay overlay-bg"></div>
	<div class="container">
		<div class="row d-flex align-items-center justify-content-center">
			<div class="about-content col-lg-12">
				<h1 class="text-white">
					{{post.title}}
				</h1>
				<p class="text-white link-nav"><a href="{% url 'website:index' %}">Home </a> <span
						class="lnr lnr-arrow-right"></span><a href="{% url 'blog:index' %}">Blog </a> <span
						class="lnr lnr-arrow-right"></span>{{post.title}}</p>
			</div>
		</div>
	</div>
</section>
<!-- End banner Area -->

<!-- Start post-content Area -->
<section class="post-content-area single-post-area">
	<div class="container">
		<div class="row">
			<div class="col-lg-8 posts-list">
				<div class="single-post row">
					<div class="col-lg-12">
						<div class="feature-img">
							<img class="img-fluid" src="{{post.image.url}}" alt="">
						</div>
					</div>
					<div class="col-lg-3  col-md-3 meta-details">
						<ul class="tags">
							{% for cat in post.category.all %}
							<li><a href="{% url 'blog:category' cat_name=cat.name %}">{{cat.name}}</a></li>{% if not forloop.last %},
							{% endif %}
							{% endfor %}
						</ul>
						<div class="user-details row">
							<p class="user-name col-lg-12 col-md-12 col-6">{% if post.author %}<a href="{% url 'blog:author' author_profile_id=post.author.id %}">{{post.author.get_full_name}}</a>{% endif %} <span
									class="lnr lnr-user"></span></p>
							<p class="date col-lg-12 col-md-12 col-6"><a href="#">{{post.published_date}}</a> <span
									class="lnr lnr-calendar-full"></span></p>
							<p class="view col-lg-12 col-md-12 col-6"><a href="#">{{post.counted_view}}</a> <span
									class="lnr lnr-eye"></span></p>
							<p class="comments col-lg-12 col-md-12 col-6"><a href="#">{{comments|length}} Comments</a> <span
									class="lnr lnr-bubble"></span></p>
							<ul class="social-links col-lg-12 col-md-12 col-6">
								<li><a href="#"><i class="fa fa-facebook"></i></a></li>
								<li><a href="#"><i class="fa fa-twitter"></i></a></li>
								<li><a href="#"><i class="fa fa-github"></i></a></li>
								<li><a href="#"><i class="fa fa-behance"></i></a></li>
							</ul>
						</div>
					</div>
					<div class="col-lg-9 col-md-9">
						<h3 class="mt-20 mb-20">{{post.title}}</h3>
						<p class="excert">
							{{post.content|safe}}
						</p>
					</div>
					<!-- <div class="col-lg-12">
						<div class="quotes">
							MCSE boot camps have its supporters and its detractors. Some people do not understand why you should have
							to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of the camp
							price. However, who has the willpower to actually sit through a self-imposed MCSE training.
						</div>
						<div class="row mt-30 mb-30">
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img1.jpg' %}" alt="">
							</div>
							<div class="col-6">
								<img class="img-fluid" src="{% static 'img/blog/post-img2.jpg' %}" alt="">
							</div>
							<div class="col-lg-12 mt-30">
								<p>
									MCSE boot camps have its supporters and its detractors. Some people do not understand why you should
									have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of
									the camp price. However, who has the willpower.
								</p>
								<p>
									MCSE boot camps have its supporters and its detractors. Some people do not understand why you should
									have to spend money on boot camp when you can get the MCSE study materials yourself at a fraction of
									the camp price. However, who has the willpower.
								</p>
							</div>
						</div>
					</div> -->
				</div>
				<div class="navigation-area">
					<div class="row">
						<div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
							<div class="thumb">
								{% if prev_post %}
								<a href="{% url 'blog:single' pid=prev_post.id %}"><img class="img-fluid"
										src="{% static 'img/blog/prev.jpg' %}" alt=""></a>
								{% else %}
								<a href="{% url 'blog:index' %}"><img class="img-fluid" src="{% static 'img/blog/prev.jpg' %}"
										alt=""></a>
								{% endif %}
							</div>
							<div class="arrow">
								{% if prev_post %}
								<a href="{% url 'blog:single' pid=prev_post.id %}"><span
										class="lnr text-white lnr-arrow-left"></span></a>
								{% else %}
								<a href="{% url 'blog:index' %}"><span class="lnr text-white lnr-arrow-left"></span></a>
								{% endif %}
							</div>
							<div class="detials">
								<p>Prev Post</p>
								{% if prev_post %}
								<a href="{% url 'blog:single' pid=prev_post.id %}">
									<h4>
										{{prev_post.title}}
									</h4>
								</a>
								{% else %}
								<a href="{% url 'blog:index' %}">
									<h4>
										Other blogs
									</h4>
								</a>
								{% endif %}

							</div>
						</div>
						<div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
							<div class="detials">
								<p>Next Post</p>
								{% if next_post %}
								<a href="{% url 'blog:single' pid=next_post.id %}">
									<h4>
										{{next_post.title}}
									</h4>
								</a>
								{% else %}
								<a href="{% url 'blog:index' %}">
									<h4>
										Other blogs
									</h4>
								</a>
								{% endif %}
							</div>
							<div class="arrow">
								{% if next_post %}
								<a href="{% url 'blog:single' pid=next_post.id %}"><span
										class="lnr text-white lnr-arrow-right"></span></a>
								{% else %}
								<a href="{% url 'blog:index' %}"><span class="lnr text-white lnr-arrow-right"></span></a>
								{% endif %}
							</div>
							<div class="thumb">
								{% if next_post %}
								<a href="{% url 'blog:single' pid=next_post.id %}"><img class="img-fluid"
										src="{% static 'img/blog/next.jpg' %}" alt=""></a>
								{% else %}
								<a href="{% url 'blog:index' %}"><img class="img-fluid" src="{% static 'img/blog/next.jpg' %}"
										alt=""></a>
								{% endif %}
							</div>
						</div>
					</div>
				</div>

				<div class="comments-area">
					<h4>{{comments|length}} Comments</h4>
					{% for comment in comments %}
					<div class="comment-list">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c1.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">{{comment.name}}</a></h5>
									<p class="date">{{comment.created_date|naturalday}} </p>
									<p class="comment">
										{{comment.message}}
									</p>
								</div>
							</div>
							<!-- <div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div> -->
						</div>
					</div>
					{% empty %}
					<div>no comments</div>
					{% endfor %}
					<!-- <div class="comment-list left-padding">
						<div class="single-comment justify-content-between d-flex">
							<div class="user justify-content-between d-flex">
								<div class="thumb">
									<img src="{% static 'img/blog/c2.jpg' %}" alt="">
								</div>
								<div class="desc">
									<h5><a href="#">Elsie Cunningham</a></h5>
									<p class="date">December 4, 2017 at 3:12 pm </p>
									<p class="comment">
										Never say goodbye till the end comes!
									</p>
								</div>
							</div>
							<div class="reply-btn">
								<a href="" class="btn-reply text-uppercase">reply</a>
							</div>
						</div>
					</div> -->

				</div>
				<div class="comment-form">
					<h4>Leave a Comment</h4>
					<form method="post" action="{% url 'blog:comment' pid=post.id %}?lastPage={{request.path}}">
						{% csrf_token %}
						<input type="hidden" name="post" value={{post.id}}>
						{% if request.user.is_authenticated %}
							<input type="hidden" name="email" value="{{request.user.email}}">		
							{% if request.user.get_full_name %}						
								<input type="hidden" name="name" value="{{request.user.get_full_name}}">
							{% else %}
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" name="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							{% endif %}
						{% else %}
						<div class="form-group form-inline">
							<div class="form-group col-lg-6 col-md-12 name">
								<input type="text" class="form-control" name="name" placeholder="Enter Name"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Name'">
							</div>
							<div class="form-group col-lg-6 col-md-12 email">
								<input type="email" class="form-control" name="email" placeholder="Enter email address"
									onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'"
									pattern="[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,4}$" title="Invalid email address" >
							</div>
						</div>
						{% endif %}
						<div class="form-group">
							<input type="text" class="form-control" name="subject" placeholder="Subject"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Subject'">
						</div>
						<div class="form-group">
							<textarea class="form-control mb-10" rows="5" name="message" placeholder="Messege"
								onfocus="this.placeholder = ''" onblur="this.placeholder = 'Messege'" required=""></textarea>
						</div>
						<button type="submit" class="primary-btn text-uppercase">Post Comment</button>
					</form>
				</div>
			</div>
			<div class="col-lg-4 sidebar-widgets">
				<div class="widget-wrap">
					{% include 'blog/blog-search.html' %}
					{% include 'blog/blog-writer.html' %}
					{% include 'blog/blog-tags.html' %}
					{% popular_posts %}
					{% include 'blog/blog-ads.html' %}
					{% include 'blog/blog-newsletter.html' %}
					


				</div>
			</div>
		</div>
	</div>
</section>
<!-- End post-content Area -->
{% endblock %}

mysite/templates/blog/blog-tags.html
{% load static %}
<div class="single-sidebar-widget tag-cloud-widget">
  <h4 class="tagcloud-title">Tag Clouds</h4>
  <ul>
    {% for tag in post.tags.all %}
    <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
    {% endfor %}
  </ul>
</div>

mysite/templates/blog/blog-writer.html
{% load static %}
 <div class="single-sidebar-widget user-info-widget">
  <img src="{% static 'img/blog/user-info.png' %}" alt="" />
  <a href="#"><h4>Charlie Barber</h4></a>
  <p>Senior blog writer</p>
  <ul class="social-links">
    <li>
      <a href="#"><i class="fa fa-facebook"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-twitter"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-github"></i></a>
    </li>
    <li>
      <a href="#"><i class="fa fa-behance"></i></a>
    </li>
  </ul>
  <p>
    Boot camps have its supporters andit sdetractors. Some people do
    not understand why you should have to spend money on boot camp
    when you can get. Boot camps have itssuppor ters andits
    detractors.
  </p>
</div>