mysite/blog/urls.py
from django.urls import path, include
from blog import views
from blog.feeds import LatestEntriesFeed

app_name = "blog"

urlpatterns = [
    path("", views.BlogView.as_view(), name="index"),
    path("<int:pid>/", views.BlogSingleView.as_view(), name="single"),
    path("comment/<int:pid>/", views.CommentView.as_view(), name="comment"),
    path("category/<str:cat_name>/", views.BlogView.as_view(), name="category"),
    path("tag/<str:tag_name>/", views.BlogView.as_view(), name="tag"),
    path("author/<int:author_profile_id>/", views.BlogView.as_view(), name="author"),
    # path('search/', views.blog_search, name='search'),
    path("api/v1/", include("blog.api.v1.urls")),
    path("rss/feed/", LatestEntriesFeed()),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap
from django.contrib.auth import views as auth_views
from rest_framework import permissions
from rest_framework.documentation import include_docs_urls
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap

sitemaps = {"static": StaticViewSitemap, "blog": BlogSitemap}

schema_view = get_schema_view(
    openapi.Info(
        title="Snippets API",
        default_version="v1",
        description="Test description",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=[permissions.AllowAny],
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("website.urls")),
    path("blog/", include("blog.urls")),
    path("accounts/", include("accounts.urls")),
    path("summernote/", include("django_summernote.urls")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("robots.txt", include("robots.urls")),
    path("captcha/", include("captcha.urls")),
    path("api-auth/", include("rest_framework.urls")),
    path("api-docs/", include_docs_urls(title="api sample")),
    # path('auth_login', accounts_views.LoginView.as_view(), name='auth_login'),
    path(
        "reset_password/", auth_views.PasswordResetView.as_view(), name="reset_password"
    ),
    path(
        "reset_password_sent/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
    path(
        "reset_password_complete/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
    # dev
    path(
        "swagger/api.json", schema_view.without_ui(cache_timeout=0), name="schema-json"
    ),
    path(
        "swagger/",
        schema_view.with_ui("swagger", cache_timeout=0),
        name="schema-swagger-ui",
    ),
    path("redoc/", schema_view.with_ui("redoc", cache_timeout=0), name="schema-redoc"),
    path("__debug__/", include("debug_toolbar.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/website/urls.py
from django.urls import path
from website import views

app_name = "website"

urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("about/", views.AboutView.as_view(), name="about"),
    path("contact/", views.ContactView.as_view(), name="contact"),
    path("newsletter/", views.NewsletterView.as_view(), name="newsletter"),
]

mysite/website/models.py
from django.db import models


class Contact(models.Model):
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255, blank=True)
    message = models.TextField()
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)


class Newsletter(models.Model):
    email = models.EmailField()

    def __str__(self):
        return self.email

mysite/website/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import Contact, Newsletter


class NameForm(forms.Form):
    name = forms.CharField(max_length=255)


class ContactForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = Contact
        fields = "__all__"

    def __init__(self, *args, **kwargs):
        super(ContactForm, self).__init__(*args, **kwargs)
        self.fields["subject"].required = False


class NewsletterForm(forms.ModelForm):
    class Meta:
        model = Newsletter
        fields = "__all__"

    def is_valid(self):
        email = self.data["email"]
        if Newsletter.objects.filter(email=email).exists():
            self.add_error("email", "your email already exists.")
        return super().is_valid()

mysite/website/views.py
from django.shortcuts import redirect
from django.views.generic import View, TemplateView, CreateView
from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from .forms import ContactForm, NewsletterForm


# def index(request):
#   return render(request, 'website/index.html')


class IndexView(TemplateView):
    template_name = "website/index.html"


# def about(request):
#   return render(request, 'website/about.html')


class AboutView(TemplateView):
    template_name = "website/about.html"


# def contact(request):
#   if request.method == 'POST':
#     form = ContactForm(request.POST)
#     if form.is_valid():
#       newform = form.save(commit=False)
#       newform.name = 'anonymous'
#       newform.save()
#       messages.success(request, 'your ticket submitted successfully.')
#     else:
#       messages.error(request, "your ticket didn't submitted.")
#   else:
#     form = ContactForm()
#   return render(request, 'website/contact.html', {'form': form})


class ContactView(SuccessMessageMixin, CreateView):
    template_name = "website/contact.html"
    form_class = ContactForm
    success_url = "/contact/"
    success_message = "your ticket submitted successfully."

    def form_invalid(self, form):
        messages.error(self.request, form.errors)
        return super().form_invalid(form)


# def newsletter(request):
#   if request.method == 'POST':
#     form = NewsletterForm(request.POST)
#     if form.is_valid():
#       form.save()
#       messages.success(request, 'your ticket submitted successfully.')
#       return HttpResponseRedirect('/')
#   messages.error(request, "your ticket didn't submitted.")
#   return HttpResponseRedirect('/')


class NewsletterView(SuccessMessageMixin, View):
    form_class = NewsletterForm

    def post(self, request, *args, **kwarg):
        form = self.form_class(request.POST)
        if form.is_valid():
            messages.success(request, "your ticket submitted successfully.")
            form.save()
        else:
            for error in form.errors.values():
                messages.error(request, error)
        path = "/"
        if last_page := request.GET.get("lastPage"):
            path = last_page
        return redirect(path)

mysite/templates/website/about.html
{% extends 'base.html' %} {% load static %} {% block container %}
<!-- start banner Area -->
<section class="about-banner relative">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">About Us</h1>
        <p class="text-white link-nav">
          <a href="index.html">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="about.html"> About Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start about-info Area -->
<section class="about-info-area section-gap">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 info-left">
        <img class="img-fluid" src="img/about/info-img.jpg" alt="" />
      </div>
      <div class="col-lg-6 info-right">
        <h6>About Us</h6>
        <h1>Who We Are?</h1>
        <p>
          Here, I focus on a range of items and features that we use in life
          without giving them a second thought. such as Coca Cola. Dolor sit
          amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt
          ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis
          nostrud exercitation ullamco.
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End about-info Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Other issues we can help you with</h1>
          <p>
            We all live in an age that belongs to the young at heart. Life that
            is.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="img/o1.jpg" alt="" />
          </div>
          <a href="#">
            <h4>Rent a Car</h4>
          </a>
          <p>
            The preservation of human life is the ultimate value, a pillar of
            ethics and the foundation.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="img/o2.jpg" alt="" />
          </div>
          <a href="#">
            <h4>Cruise Booking</h4>
          </a>
          <p>
            I was always somebody who felt quite sorry for myself, what I had
            not got compared.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="img/o3.jpg" alt="" />
          </div>
          <a href="#">
            <h4>To Do List</h4>
          </a>
          <p>
            The following article covers a topic that has recently moved to
            center stage–at least it seems.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="img/o4.jpg" alt="" />
          </div>
          <a href="#">
            <h4>Food Features</h4>
          </a>
          <p>
            There are many kinds of narratives and organizing principles.
            Science is driven by evidence.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End other-issue Area -->
{% endblock %}

mysite/templates/website/contact.html
{% extends 'base.html' %} {% load static %} {% block container %}
<!-- start banner Area -->
<section class="relative about-banner">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row d-flex align-items-center justify-content-center">
      <div class="about-content col-lg-12">
        <h1 class="text-white">Contact Us</h1>
        <p class="text-white link-nav">
          <a href="index.html">Home </a>
          <span class="lnr lnr-arrow-right"></span>
          <a href="contact.html"> Contact Us</a>
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start contact-page Area -->
<section class="contact-page-area section-gap">
  <div class="container">
    <div class="row">
      <div class="map-wrap" style="width: 100%; height: 445px" id="map"></div>
      <div class="col-lg-4 d-flex flex-column address-wrap">
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-home"></span>
          </div>
          <div class="contact-details">
            <h5>Binghamton, New York</h5>
            <p>4343 Hinkle Deegan Lake Road</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-phone-handset"></span>
          </div>
          <div class="contact-details">
            <h5>00 (958) 9865 562</h5>
            <p>Mon to Fri 9am to 6 pm</p>
          </div>
        </div>
        <div class="single-contact-address d-flex flex-row">
          <div class="icon">
            <span class="lnr lnr-envelope"></span>
          </div>
          <div class="contact-details">
            <h5>support@colorlib.com</h5>
            <p>Send us your query anytime!</p>
          </div>
        </div>
      </div>
      <div class="col-lg-8">
        <form class="form-area contact-form text-right" action="{% url 'website:contact' %}" method="post">
          {% csrf_token %}
          <div class="row">
            <div class="col-lg-6 form-group">
              <input name="name" placeholder="Enter your name" onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter your name'" class="common-input mb-20 form-control" required=""
                type="text" />

              <input name="email" placeholder="Enter email address"
                pattern="[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{1,63}$" onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter email address'" class="common-input mb-20 form-control" required=""
                type="email" />

              <input name="subject" placeholder="Enter subject" onfocus="this.placeholder = ''"
                onblur="this.placeholder = 'Enter subject'" class="common-input mb-20 form-control" type="text" />
                  
            </div>
            <div class="col-lg-6 form-group">
              <textarea class="common-textarea form-control" name="message" placeholder="Enter Messege"
                onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Messege'" required=""></textarea>
            </div>
       
            <div class="col-lg-12">
              <div calss="common-input mb-20 form-control pb-3" >
                {{form.captcha}}
              </div>  
              <div class="alert-msg" style="text-align: left"></div>
              <button type="submit" class="genric-btn primary" style="float: right">
                Send Message
              </button>
            </div>
          </div>
        </form>
        
        {% if form.errors %}
        <div class="alert alert-error">
          <h4>Please fix the following errors</h4>
          <ul>
            {% for field in form %}
            {% if field.errors %}
            {% for error in field.errors %}
            <li>{{ error|escape }}</li>
            {% endfor %}
            {% endif %}
            {% endfor %}
          </ul>
          {% if form.non_field_errors %}
          {{ form.non_field_errors }}
          {% endif %}
        </div>
        {% endif %}
      </div>
    </div>
  </div>
</section>
<!-- End contact-page Area -->
{% endblock %}

mysite/templates/website/index.html
{% extends 'base.html' %} 
{% load static %}
{% load website_tags %} 
{% block container %}
<!-- start banner Area -->
<section class="banner-area relative">
  <div class="overlay overlay-bg"></div>
  <div class="container">
    <div class="row fullscreen align-items-center justify-content-between">
      <div class="col-lg-6 col-md-6 banner-left">
        <h6 class="text-white">Away from monotonous life</h6>
        <h1 class="text-white">Magical Travel</h1>
        <p class="text-white">
          If you are looking at blank cassettes on the web, you may be very
          confused at the difference in price. You may see some for as low as
          $.17 each.
        </p>
      </div>
    </div>
  </div>
</section>
<!-- End banner Area -->

<!-- Start popular-destination Area -->
<section class="popular-destination-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-8">
        <div class="title text-center">
          <h1 class="mb-10">Popular Destinations</h1>
          <p>
            We all live in an age that belongs to the young at heart. Life that
            is becoming extremely fast, day.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-4">
        <div class="single-destination relative">
          <div class="thumb relative">
            <div class="overlay overlay-bg"></div>
            <img class="img-fluid" src="{% static 'img/d1.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <a href="#" class="price-btn">$150</a>
            <h4>Mountain River</h4>
            <p>Paraguay</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-destination relative">
          <div class="thumb relative">
            <div class="overlay overlay-bg"></div>
            <img class="img-fluid" src="{% static 'img/d2.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <a href="#" class="price-btn">$250</a>
            <h4>Dream City</h4>
            <p>Paris</p>
          </div>
        </div>
      </div>
      <div class="col-lg-4">
        <div class="single-destination relative">
          <div class="thumb relative">
            <div class="overlay overlay-bg"></div>
            <img class="img-fluid" src="{% static 'img/d3.jpg' %}" alt="" />
          </div>
          <div class="desc">
            <a href="#" class="price-btn">$350</a>
            <h4>Cloud Mountain</h4>
            <p>Sri Lanka</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End popular-destination Area -->

<!-- Start other-issue Area -->
<section class="other-issue-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-70 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Other issues we can help you with</h1>
          <p>
            We all live in an age that belongs to the young at heart. Life that
            is.
          </p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o1.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Rent a Car</h4>
          </a>
          <p>
            The preservation of human life is the ultimate value, a pillar of
            ethics and the foundation.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o2.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Cruise Booking</h4>
          </a>
          <p>
            I was always somebody who felt quite sorry for myself, what I had
            not got compared.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o3.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>To Do List</h4>
          </a>
          <p>
            The following article covers a topic that has recently moved to
            center stage–at least it seems.
          </p>
        </div>
      </div>
      <div class="col-lg-3 col-md-6">
        <div class="single-other-issue">
          <div class="thumb">
            <img class="img-fluid" src="{% static 'img/o4.jpg' %}" alt="" />
          </div>
          <a href="#">
            <h4>Food Features</h4>
          </a>
          <p>
            There are many kinds of narratives and organizing principles.
            Science is driven by evidence.
          </p>
        </div>
      </div>
    </div>
  </div>
</section>
<!-- End other-issue Area -->

<!-- Start home-about Area -->
<section class="home-about-area">
  <div class="container-fluid">
    <div class="row align-items-center justify-content-end">
      <div class="col-lg-6 col-md-12 home-about-left">
        <h1>
          Did not find your Package? <br />
          Feel free to ask us. <br />
          We‘ll make it for you
        </h1>
        <p>
          inappropriate behavior is often laughed off as “boys will be boys,”
          women face higher conduct standards especially in the workplace.
          That’s why it’s crucial that, as women, our behavior on the job is
          beyond reproach. inappropriate behavior is often laughed.
        </p>
        <a href="#" class="primary-btn text-uppercase">request custom price</a>
      </div>
      <div class="col-lg-6 col-md-12 home-about-right no-padding">
        <img class="img-fluid" src="{% static 'img/about-img.jpg' %}" alt="" />
      </div>
    </div>
  </div>
</section>
<!-- End home-about Area -->

<!-- Start blog Area -->
{% latest_post %}
<!-- End recent-blog Area -->
{% endblock %}

mysite/templates/website/latest-blog.html
{% load static %}
<!-- Start blog Area -->
<section class="recent-blog-area section-gap">
  <div class="container">
    <div class="row d-flex justify-content-center">
      <div class="menu-content pb-60 col-lg-9">
        <div class="title text-center">
          <h1 class="mb-10">Latest from Our Blog</h1>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="active-recent-blog-carusel">
        {% for post in posts %}
        <div class="single-recent-blog-post item">
          <div class="thumb">
            <img class="img-fluid" src="{{post.image.url}}" alt="" />
          </div>
          <div class="details">
            <div class="tags">
              <ul>
                {% for cat in post.category.all %}
                <li>
                  <a href="{% url 'blog:category' cat_name=cat.name %}">{{cat}}</a>
                </li> 
                {% endfor %}
              </ul>
            </div>
            <a href="{% url 'blog:single' pid=post.id %}"><h4 class="title">{{post.title}}</h4></a>
            <p>
              {{post.content|truncatechars:30}}
            </p>
            <h6 class="date">{{post.published_date|date:"d M Y"}}</h6>
          </div>
        </div>
        {% endfor %}
      </div>
    </div>
  </div>
</section>
<!-- End recent-blog Area -->

mysite/templates/website/messages.html
{% load static %}
{% for message in messages %}
    <div class="alert {{ message.tags }} alert-dismissible" role="alert" style=" position: fixed;  top: 50%;  left: 50%;  transform: translate(-50%, -50%);  width: 50%;">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="True">&times;</span>
      </button>
      {{ message }}
    </div>
{% endfor %}